add job inheritance
Signed-off-by: Kirill Ganigin <kirill.ganigin@dsr-corporation.com>

diff --git a/.github/workflows/callable_test-automation.yaml b/.github/workflows/callable_test-automation.yaml
--- a/.github/workflows/callable_test-automation.yaml
+++ b/.github/workflows/callable_test-automation.yaml
@@ -555,10 +555,74 @@ jobs:
 #          name: detailed-test-result-test_consensus
 #          path: test-result-indy-test-automation-${{ matrix.module }}-payment.txt
 #          retention-days: 5
-  Tests:
-      name: VDR
-      uses: hyperledger/indy-test-automation/matrix_test_action.yaml@v1
-      with:
-        modules-json: ${{ needs.get-test-modules.outputs.modules }}
-        test-path: ${{ env.TEST_DIRECTORY_PAYMENT }}
-        include-payment-tests: ${{ env.INCLUDE_PAYMENT_TESTS }}
+
+  MatrixTest:
+    name: MatrixTest
+    needs: [ workflow-setup, node-image, client-image, get-test-modules ]
+    runs-on: ubuntu-20.04
+    env:
+      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
+    strategy:
+      matrix:
+        module: ${{ fromJson(needs.get-test-modules.outputs.modules) }}
+        test-path: ${{ TEST_DIRECTORY }}
+        include:
+          module: ${{ fromJson(needs.get-test-modules.outputs.payment-modules) }}
+          test-path: ${{ TEST_DIRECTORY_PAYMENT }}
+      fail-fast: false
+    steps:
+      - name: Git checkout MeltedGlaciers/indy-test-automation
+        uses: actions/checkout@v3
+        with:
+          repository: MeltedGlaciers/indy-test-automation
+          ref: ${{ env.TEST_AUTOMATION_BRANCH }}
+
+      - name: Create docker network
+        run: |
+          docker network create --subnet="${{ env.NETWORK_SUBNET }}" "${{ env.NETWORK_NAME }}"
+      - name: Download client artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: client_image
+          path: /tmp
+
+      - name: Download node artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: node_image
+          path: /tmp
+
+      - name: Load client and node image
+        run: |
+          docker load --input /tmp/client_image_${{ env.INPUT_UBUNTUVERSION }}.tar
+          docker load --input /tmp/node_image_${{ env.INPUT_UBUNTUVERSION }}.tar
+      - name: ${{ matrix.module }}
+        id: test_Matrix
+        run: |
+          cd ./system/docker
+          TEST_PARAMS="-l -v --junit-xml=${{ matrix.module }}-report.xml"
+          if [[ ${INCLUDE_PAYMENT_TESTS} == "true" ]]; then
+            TEST_PARAMS+="${TEST_PARAMS} --payments"
+          fi
+          UBUNTU_VERSION="${{ env.INPUT_UBUNTUVERSION }}" \
+          IMAGE_REPOSITORY="ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/" \
+          CLIENT_IMAGE="client:${{ env.INPUT_UBUNTUVERSION }}" \
+          NODE_IMAGE="node-${{ env.INPUT_UBUNTUVERSION }}" \
+          ./run.sh ${{ matrix.test_path }}/${{ matrix.module }}.py "${TEST_PARAMS}" ${{ env.NETWORK_NAME }}
+      - name: Publish Test Report
+        if: success() || failure()
+        uses: scacap/action-surefire-report@v1
+        continue-on-error: true
+        with:
+          check_name: ${{ matrix.test_path }}\${{ matrix.module }} Test Report
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          report_paths: "*-report.xml"
+
+      - name: Upload Detailed Test Failure Results
+        # The test runner only emits the detailed test results if the tests fail.
+        if: (steps.test_Matrix == 'failure') && failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: detailed-test-result-test_consensus
+          path: test-result-indy-test-automation-${{ matrix.module }}-${{ matrix.test_path }}.txt
+          retention-days: 5
