separate test matrices
Signed-off-by: Kirill Ganigin <kirill.ganigin@dsr-corporation.com>

diff --git a/.github/workflows/callable_test-automation.yaml b/.github/workflows/callable_test-automation.yaml
--- a/.github/workflows/callable_test-automation.yaml
+++ b/.github/workflows/callable_test-automation.yaml
@@ -43,7 +43,7 @@ on:
         description: "The directory, relative to the indy-test-automantion project folder, containing the tests to be executed."
         required: false
         type: string
-        default: "system_payments_only/indy-node-tests"
+        default: "system/indy-node-tests"
       includePaymentTests:
         description: "Include payment tests.  Defaults to false."
         required: false
@@ -100,7 +100,7 @@ on:
         description: "The directory, relative to the indy-test-automantion project folder, containing the tests to be executed."
         required: false
         type: string
-        default: "system_payments_only/indy-node-tests"
+        default: "system/indy-node-tests"
       includePaymentTests:
         description: "Include payment tests.  Defaults to false."
         required: false
@@ -136,8 +136,9 @@ env:
 
   NETWORK_NAME: "indy-test-automation-network"
   NETWORK_SUBNET: "10.0.0.0/24"
-  TEST_DIRECTORY: "system_payments_only/indy-node-tests"
+  TEST_DIRECTORY: "system/indy-node-tests"
   INCLUDE_PAYMENT_TESTS: true
+  TEST_DIRECTORY_PAYMENT: "system_payments_only/indy-node-tests"
 
 jobs:
   workflow-setup:
@@ -261,15 +262,15 @@ jobs:
 #        uses: actions/download-artifact@v3
 #        with:
 #          name: sovrin.deb
-#          path: ./system_payments_only/docker/node/
+#          path: ./system/docker/node/
       - name: LS DEBUG
-        run: ls ./system_payments_only/docker/node/
+        run: ls ./system/docker/node/
       - name: Build and cache image
         if: steps.cache-image.outputs.cache-hit != 'true'
         uses: docker/build-push-action@v3
         with:
-          context: ./system_payments_only/docker/node
-          file: ./system_payments_only/docker/node/Dockerfile.${{ env.INPUT_UBUNTUVERSION }}
+          context: ./system/docker/node
+          file: ./system/docker/node/Dockerfile.${{ env.INPUT_UBUNTUVERSION }}
           push: false
           tags: ${{ steps.prep.outputs.tags }}
           labels: |
@@ -336,8 +337,8 @@ jobs:
       - name: Build and cache image
         uses: docker/build-push-action@v3
         with:
-          context: ./system_payments_only/docker/client/
-          file: ./system_payments_only/docker/client/Dockerfile.${{ env.INPUT_UBUNTUVERSION }}
+          context: ./system/docker/client/
+          file: ./system/docker/client/Dockerfile.${{ env.INPUT_UBUNTUVERSION }}
           push: false
           tags: ${{ steps.prep.outputs.tags }}
           labels: |
@@ -370,6 +371,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       modules: ${{ steps.get-module-list.outputs.file_names }}
+      payment_modules: ${{ steps.get-payment-module-list.outputs.file_names }}
     steps:
       - name: Git checkout MeltedGlaciers/indy-test-automation
         uses: actions/checkout@v3
@@ -399,10 +401,32 @@ jobs:
           # ==============================================
           ignore_files_starts_with: ""
 
+      - name: Get Payment Module List
+        id: get-payment-module-list
+        uses: the-coding-turtle/ga-file-list@v0.4.1
+        with:
+          directory: ${{ env.TEST_DIRECTORY_PAYMENT }}
+          file_extension: "py"
+
+          # ==============================================
+          # Include all tests by default.
+          # ==============================================
+          only_files_starts_with: "test,Test"
+
+          # ==============================================
+          # Ignore specific test harnesses here
+          # ----------------------------------------------
+          # Ignore tests by renaming the file for the
+          # test to have a prefix of "skip-". Line below
+          # is not really needed, but left in to make
+          # it clear the files are being ignored.
+          # ==============================================
+          ignore_files_starts_with: ""
+
   ### 1 Job in workflow per test
   ### The tests rely on docker in docker with the fixed network name and fixed IP addresses.
-  MatrixTest:
-    name: MatrixTest
+  MatrixTestVDR:
+    name: MatrixTestVDR
     needs: [ workflow-setup, node-image, client-image, get-test-modules]
     runs-on: ubuntu-20.04
     env:
@@ -437,10 +461,10 @@ jobs:
         run: |
           docker load --input /tmp/client_image_${{ env.INPUT_UBUNTUVERSION }}.tar
           docker load --input /tmp/node_image_${{ env.INPUT_UBUNTUVERSION }}.tar
-      - name: ${{ matrix.module }}
+      - name: VDR-${{ matrix.module }}
         id: test_Matrix
         run: |
-          cd ./system_payments_only/docker
+          cd ./system/docker
           TEST_PARAMS="-l -v --junit-xml=${{ matrix.module }}-report.xml"
           if [[ ${INCLUDE_PAYMENT_TESTS} == "true" ]]; then
             TEST_PARAMS+="${TEST_PARAMS} --payments"
@@ -455,7 +479,7 @@ jobs:
         uses: scacap/action-surefire-report@v1
         continue-on-error: true
         with:
-          check_name: ${{ matrix.module }} Test Report
+          check_name: VDR-${{ matrix.module }} Test Report
           github_token: ${{ secrets.GITHUB_TOKEN }}
           report_paths: "*-report.xml"
 
@@ -465,5 +489,72 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: detailed-test-result-test_consensus
-          path: test-result-indy-test-automation-${{ matrix.module }}.txt
+          path: test-result-indy-test-automation-${{ matrix.module }}-vdr.txt
+          retention-days: 5
+
+  MatrixTestPayments:
+    name: MatrixTestPayments
+    needs: [ workflow-setup, node-image, client-image, get-test-modules ]
+    runs-on: ubuntu-20.04
+    env:
+      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
+    strategy:
+      matrix:
+        module: ${{ fromJson(needs.get-test-modules.outputs.payment-modules) }}
+      fail-fast: false
+    steps:
+      - name: Git checkout MeltedGlaciers/indy-test-automation
+        uses: actions/checkout@v3
+        with:
+          repository: MeltedGlaciers/indy-test-automation
+          ref: ${{ env.TEST_AUTOMATION_BRANCH }}
+
+      - name: Create docker network
+        run: |
+          docker network create --subnet="${{ env.NETWORK_SUBNET }}" "${{ env.NETWORK_NAME }}"
+      - name: Download client artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: client_image
+          path: /tmp
+
+      - name: Download node artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: node_image
+          path: /tmp
+
+      - name: Load client and node image
+        run: |
+          docker load --input /tmp/client_image_${{ env.INPUT_UBUNTUVERSION }}.tar
+          docker load --input /tmp/node_image_${{ env.INPUT_UBUNTUVERSION }}.tar
+      - name: Payment-${{ matrix.module }}
+        id: test_Matrix
+        run: |
+          cd ./system_payments_only/docker
+          TEST_PARAMS="-l -v --junit-xml=${{ matrix.module }}-report.xml"
+          if [[ ${INCLUDE_PAYMENT_TESTS} == "true" ]]; then
+            TEST_PARAMS+="${TEST_PARAMS} --payments"
+          fi
+          UBUNTU_VERSION="${{ env.INPUT_UBUNTUVERSION }}" \
+          IMAGE_REPOSITORY="ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/" \
+          CLIENT_IMAGE="client:${{ env.INPUT_UBUNTUVERSION }}" \
+          NODE_IMAGE="node-${{ env.INPUT_UBUNTUVERSION }}" \
+          ./run.sh ${{ env.TEST_DIRECTORY_PAYMENT }}/${{ matrix.module }}.py "${TEST_PARAMS}" ${{ env.NETWORK_NAME }}
+      - name: Publish Test Report
+        if: success() || failure()
+        uses: scacap/action-surefire-report@v1
+        continue-on-error: true
+        with:
+          check_name: Payment-${{ matrix.module }} Test Report
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          report_paths: "*-report.xml"
+
+      - name: Upload Detailed Test Failure Results
+        # The test runner only emits the detailed test results if the tests fail.
+        if: (steps.test_Matrix == 'failure') && failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: detailed-test-result-test_consensus
+          path: test-result-indy-test-automation-${{ matrix.module }}-payment.txt
           retention-days: 5
